### ISSUE TITLE
Documentation: 3rd role should be "...::Atomic"

### ISSUE THREAD

**Issue by eserte** [maxmind/Stepford#22]
See https://metacpan.org/pod/release/MAXMIND/Stepford-0.003005/lib/Stepford.pm#DESCRIPTION
--- the 1st and 3rd role are the same, probably you meant Stepford::Role::Step::FileGenerator::Atomic as the 3rd available role.

**Comment by autarch** [comment]
Thanks, I just pushed a fix for this.
